### ISSUE TITLE
[Bug] Failed to upload to Play Console: NoSuchMethodError: Class 'String' has no instance method 'capitalize'.     

### ISSUE THREAD

**Issue by karlreginaldo** [andrewpmoore/simple_deploy#2]
![image](https://github.com/user-attachments/assets/01ac88df-83fa-4d20-853c-2cfe12db1f75)

**Comment by andrewpmoore** [comment]
Thanks for the pull request, this is now merged 👍

**Comment by karlreginaldo** [comment]
This is really great package btw! now I can drink a coffee while deploying to internal testing

**Comment by andrewpmoore** [comment]
Thanks, really appreciate the pr, love the cursor animating!
