### ISSUE TITLE
Upload to TestFlight Failed - Unable to Find Archive File (IPA has a different name than app.ipa)

### ISSUE THREAD

**Issue by samuelquaynor** [andrewpmoore/simple_deploy#5]
Attempting to upload the app to TestFlight resulted in an error indicating that the archive file could not be found. But archive is available just in a different name, is there accomodation to set archive with a different name?

Error: Upload to TestFlight failed: Running altool at path '/Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Frameworks/AppStoreService.framework/Support/altool'...
2024-11-11 12:52:41.882 *** Error: Error uploading '/Users/samuelquaynor/Documents/GitHub/ntemm_rider/build/ios/ipa/app.ipa'.
2024-11-11 12:52:41.883 *** Error: Unable to upload archive. The file '/Users/samuelquaynor/Documents/GitHub/ntemm_rider/build/ios/ipa/app.ipa' cannot be found. (-43)
{
    NSLocalizedDescription = "Unable to upload archive.";
    NSLocalizedFailureReason = "The file '/Users/samuelquaynor/Documents/GitHub/ntemm_rider/build/ios/ipa/app.ipa' cannot be found.";
}

![Screenshot 2024-11-11 at 12 57 47](https://github.com/user-attachments/assets/36aec0d5-127a-48f4-b56b-e47b1aabbaf4)

**Comment by andrewpmoore** [comment]
At the moment it's assuming app.ipa as that's `flutter build ios creates` I think.
I'm curious as to understand how it gets that name, I can certainly look at adding in a buidName

**Comment by andrewpmoore** [comment]
In version 0.21.0 you can now specify a generatedFileName which will override the default app.ipa. Give it a go and re-open the issue if you have any issues with it

**Comment by samuelquaynor** [comment]
Working now thanks
